"""Closed vocabularies used for structural routing and verification."""

from enum import StrEnum


class ProvenanceKind(StrEnum):
    REAL = "REAL"
    MOCK = "MOCK"
    SIMULATED = "SIMULATED"


class SearchType(StrEnum):
    DIRECT = "DIRECT"
    OPTUNA = "OPTUNA"
    OPENEVOLVE = "OPENEVOLVE"


class HypothesisStatus(StrEnum):
    OPEN = "OPEN"
    SUPPORTED = "SUPPORTED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class EvidenceStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class RunStatus(StrEnum):
    INITIALISING = "INITIALISING"
    RUNNING = "RUNNING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


class EventType(StrEnum):
    RUN_INITIALISED = "RUN_INITIALISED"
    HYPOTHESIS_PROPOSED = "HYPOTHESIS_PROPOSED"
    SEARCH_PLANNED = "SEARCH_PLANNED"
    HUMAN_DECISION = "HUMAN_DECISION"
    EXPERIMENT_PREPARED = "EXPERIMENT_PREPARED"
    BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
    EVALUATION_OBSERVED = "EVALUATION_OBSERVED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    OPTUNA_STUDY_STARTED = "OPTUNA_STUDY_STARTED"
    OPTUNA_TRIAL_PROPOSED = "OPTUNA_TRIAL_PROPOSED"
    OPTUNA_TRIAL_REPORTED = "OPTUNA_TRIAL_REPORTED"
    OPTUNA_STUDY_COMPLETED = "OPTUNA_STUDY_COMPLETED"
    RUN_STOPPED = "RUN_STOPPED"
