"""Closed vocabularies used for structural routing and verification."""

from enum import StrEnum


class ProvenanceKind(StrEnum):
    REAL = "REAL"
    MOCK = "MOCK"
    SIMULATED = "SIMULATED"


class ProposalSource(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    MODEL_GENERATED = "MODEL_GENERATED"
    HUMAN = "HUMAN"
    KNOWLEDGE_GROUNDED = "KNOWLEDGE_GROUNDED"


class GroundingStatus(StrEnum):
    UNGROUNDED = "UNGROUNDED"
    CONTRACT_GROUNDED = "CONTRACT_GROUNDED"
    PRIOR_RESULTS_GROUNDED = "PRIOR_RESULTS_GROUNDED"
    KNOWLEDGE_GROUNDED = "KNOWLEDGE_GROUNDED"


class AgentRole(StrEnum):
    HYPOTHESIS = "HYPOTHESIS"
    PLANNER = "PLANNER"


class AgentCallStatus(StrEnum):
    RESERVED = "RESERVED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INDETERMINATE = "INDETERMINATE"


class ProviderErrorCode(StrEnum):
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    TIMEOUT = "TIMEOUT"
    TRANSIENT_PROVIDER_ERROR = "TRANSIENT_PROVIDER_ERROR"
    INVALID_STRUCTURED_OUTPUT = "INVALID_STRUCTURED_OUTPUT"
    CONTEXT_TOO_LARGE = "CONTEXT_TOO_LARGE"
    PERMANENT_PROVIDER_ERROR = "PERMANENT_PROVIDER_ERROR"


class SearchType(StrEnum):
    DIRECT = "DIRECT"
    OPTUNA = "OPTUNA"
    OPENEVOLVE = "OPENEVOLVE"


class HypothesisStatus(StrEnum):
    OPEN = "OPEN"
    SUPPORTED = "SUPPORTED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class EvidenceStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class RunStatus(StrEnum):
    INITIALISING = "INITIALISING"
    RUNNING = "RUNNING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


class EventType(StrEnum):
    RUN_INITIALISED = "RUN_INITIALISED"
    HYPOTHESIS_PROPOSED = "HYPOTHESIS_PROPOSED"
    SEARCH_PLANNED = "SEARCH_PLANNED"
    HUMAN_DECISION = "HUMAN_DECISION"
    EXPERIMENT_PREPARED = "EXPERIMENT_PREPARED"
    BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
    EVALUATION_OBSERVED = "EVALUATION_OBSERVED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    OPTUNA_STUDY_STARTED = "OPTUNA_STUDY_STARTED"
    OPTUNA_TRIAL_PROPOSED = "OPTUNA_TRIAL_PROPOSED"
    OPTUNA_TRIAL_REPORTED = "OPTUNA_TRIAL_REPORTED"
    OPTUNA_STUDY_COMPLETED = "OPTUNA_STUDY_COMPLETED"
    MODEL_CALL_RESERVED = "MODEL_CALL_RESERVED"
    MODEL_CALL_COMPLETED = "MODEL_CALL_COMPLETED"
    MODEL_CALL_FAILED = "MODEL_CALL_FAILED"
    RUN_STOPPED = "RUN_STOPPED"
