"""Closed vocabularies used for structural routing and verification."""

from enum import StrEnum


class ProvenanceKind(StrEnum):
    REAL = "REAL"
    MOCK = "MOCK"
    SIMULATED = "SIMULATED"


class ProposalSource(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    MODEL_GENERATED = "MODEL_GENERATED"
    HUMAN = "HUMAN"
    KNOWLEDGE_GROUNDED = "KNOWLEDGE_GROUNDED"


class GroundingStatus(StrEnum):
    UNGROUNDED = "UNGROUNDED"
    CONTRACT_GROUNDED = "CONTRACT_GROUNDED"
    PRIOR_RESULTS_GROUNDED = "PRIOR_RESULTS_GROUNDED"
    KNOWLEDGE_GROUNDED = "KNOWLEDGE_GROUNDED"


class KnowledgeGroundingMode(StrEnum):
    DISABLED = "DISABLED"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"


class ReadSafetyMode(StrEnum):
    """Closed assurance vocabulary for external knowledge reads."""

    PRIVILEGE_VERIFIED = "PRIVILEGE_VERIFIED"
    OPERATOR_ATTESTED = "OPERATOR_ATTESTED"
    UNVERIFIED = "UNVERIFIED"


class KnowledgeRetrievalStatus(StrEnum):
    DISABLED = "DISABLED"
    RESERVED = "RESERVED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INDETERMINATE = "INDETERMINATE"


class AgentRole(StrEnum):
    HYPOTHESIS = "HYPOTHESIS"
    PLANNER = "PLANNER"
    OPENEVOLVE_MUTATION = "OPENEVOLVE_MUTATION"


class AgentCallStatus(StrEnum):
    RESERVED = "RESERVED"
    DISPATCHING = "DISPATCHING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INDETERMINATE = "INDETERMINATE"
    FAILED_BEFORE_DISPATCH = "FAILED_BEFORE_DISPATCH"
    FAILED_CONFIRMED = "FAILED_CONFIRMED"
    OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN"
    REJECTED = "REJECTED"


class ProviderErrorCode(StrEnum):
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    TIMEOUT = "TIMEOUT"
    TRANSIENT_PROVIDER_ERROR = "TRANSIENT_PROVIDER_ERROR"
    INVALID_STRUCTURED_OUTPUT = "INVALID_STRUCTURED_OUTPUT"
    CONTEXT_TOO_LARGE = "CONTEXT_TOO_LARGE"
    PERMANENT_PROVIDER_ERROR = "PERMANENT_PROVIDER_ERROR"
    PROVIDER_UNAVAILABLE_BEFORE_DISPATCH = "PROVIDER_UNAVAILABLE_BEFORE_DISPATCH"
    PROVIDER_CONFIRMED_FAILURE = "PROVIDER_CONFIRMED_FAILURE"
    OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN"
    RESPONSE_INVALID = "RESPONSE_INVALID"
    COMPLETION_PERSISTENCE_FAILED = "COMPLETION_PERSISTENCE_FAILED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"


class SearchType(StrEnum):
    DIRECT = "DIRECT"
    OPTUNA = "OPTUNA"
    OPENEVOLVE = "OPENEVOLVE"


class HypothesisStatus(StrEnum):
    OPEN = "OPEN"
    SUPPORTED = "SUPPORTED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class EvidenceStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class RunStatus(StrEnum):
    INITIALISING = "INITIALISING"
    RUNNING = "RUNNING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


class EventType(StrEnum):
    RUN_INITIALISED = "RUN_INITIALISED"
    HYPOTHESIS_PROPOSED = "HYPOTHESIS_PROPOSED"
    SEARCH_PLANNED = "SEARCH_PLANNED"
    HUMAN_DECISION = "HUMAN_DECISION"
    EXPERIMENT_PREPARED = "EXPERIMENT_PREPARED"
    BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
    EVALUATION_OBSERVED = "EVALUATION_OBSERVED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    OPTUNA_STUDY_STARTED = "OPTUNA_STUDY_STARTED"
    OPTUNA_TRIAL_PROPOSED = "OPTUNA_TRIAL_PROPOSED"
    OPTUNA_TRIAL_REPORTED = "OPTUNA_TRIAL_REPORTED"
    OPTUNA_STUDY_COMPLETED = "OPTUNA_STUDY_COMPLETED"
    OPENEVOLVE_SEARCH_INITIALISED = "OPENEVOLVE_SEARCH_INITIALISED"
    OPENEVOLVE_GENERATION_STARTED = "OPENEVOLVE_GENERATION_STARTED"
    OPENEVOLVE_MUTATION_RESERVED = "OPENEVOLVE_MUTATION_RESERVED"
    OPENEVOLVE_CANDIDATE_PROPOSED = "OPENEVOLVE_CANDIDATE_PROPOSED"
    OPENEVOLVE_CANDIDATE_REJECTED = "OPENEVOLVE_CANDIDATE_REJECTED"
    OPENEVOLVE_CANDIDATE_PREPARED = "OPENEVOLVE_CANDIDATE_PREPARED"
    OPENEVOLVE_CANDIDATE_EVALUATED = "OPENEVOLVE_CANDIDATE_EVALUATED"
    OPENEVOLVE_CANDIDATE_VERIFIED = "OPENEVOLVE_CANDIDATE_VERIFIED"
    OPENEVOLVE_PARENT_SELECTED = "OPENEVOLVE_PARENT_SELECTED"
    OPENEVOLVE_POPULATION_UPDATED = "OPENEVOLVE_POPULATION_UPDATED"
    OPENEVOLVE_GENERATION_COMPLETED = "OPENEVOLVE_GENERATION_COMPLETED"
    OPENEVOLVE_SEARCH_STOPPED = "OPENEVOLVE_SEARCH_STOPPED"
    MODEL_CALL_RESERVED = "MODEL_CALL_RESERVED"
    MODEL_CALL_COMPLETED = "MODEL_CALL_COMPLETED"
    MODEL_CALL_FAILED = "MODEL_CALL_FAILED"
    LIVE_MUTATION_DISPATCHED = "LIVE_MUTATION_DISPATCHED"
    LIVE_MUTATION_OUTCOME_UNKNOWN = "LIVE_MUTATION_OUTCOME_UNKNOWN"
    KNOWLEDGE_RETRIEVAL_RESERVED = "KNOWLEDGE_RETRIEVAL_RESERVED"
    KNOWLEDGE_RETRIEVAL_COMPLETED = "KNOWLEDGE_RETRIEVAL_COMPLETED"
    KNOWLEDGE_RETRIEVAL_FAILED = "KNOWLEDGE_RETRIEVAL_FAILED"
    KNOWLEDGE_BUNDLE_VALIDATED = "KNOWLEDGE_BUNDLE_VALIDATED"
    RUN_STOPPED = "RUN_STOPPED"
