"""Generic resource admission, brokerage, telemetry, and leasing."""

from auto_researcher.resources.broker import (
    CourtesyResourceAdmissionPolicy,
    InvalidResourceRequest,
    InvalidResourceState,
    ResourceBroker,
    ResourceBrokerError,
    ResourceInspectionError,
    ResourceWaitTimeout,
)
from auto_researcher.resources.leases import (
    InMemoryResourceLeaseStore,
    PostgresResourceLeaseStore,
    ResourceLeaseConflict,
    ResourceLeaseError,
    ResourceLeaseNotFound,
    ResourceLeaseOwnershipError,
    ResourceLeaseStoreUnavailable,
)
from auto_researcher.resources.models import (
    AdmissionClass,
    AdmissionOutcome,
    PreemptionPolicy,
    ResourceAdmission,
    ResourceAdmissionDecision,
    ResourceAdmissionTelemetry,
    ResourceCandidate,
    ResourceCapacity,
    ResourceLease,
    ResourceOwner,
    ResourceRequest,
    ResourceRequirement,
)
from auto_researcher.resources.nvidia import (
    InvalidGPUProviderSnapshot,
    NvidiaComputeProcess,
    NvidiaGPUObservation,
    NvidiaGPUResourceProvider,
    NvidiaSmiGPUEnumerator,
    cuda_environment_for_lease,
    physical_gpu_index,
)
from auto_researcher.resources.protocols import (
    ResourceAdmissionPolicy,
    ResourceLeaseStore,
    ResourceProvider,
)

__all__ = [
    "AdmissionClass",
    "AdmissionOutcome",
    "CourtesyResourceAdmissionPolicy",
    "InMemoryResourceLeaseStore",
    "PostgresResourceLeaseStore",
    "InvalidResourceRequest",
    "InvalidResourceState",
    "InvalidGPUProviderSnapshot",
    "NvidiaComputeProcess",
    "NvidiaGPUObservation",
    "NvidiaGPUResourceProvider",
    "NvidiaSmiGPUEnumerator",
    "PreemptionPolicy",
    "ResourceAdmission",
    "ResourceAdmissionDecision",
    "ResourceAdmissionPolicy",
    "ResourceAdmissionTelemetry",
    "ResourceBroker",
    "ResourceBrokerError",
    "ResourceCandidate",
    "ResourceCapacity",
    "ResourceInspectionError",
    "ResourceLease",
    "ResourceLeaseConflict",
    "ResourceLeaseError",
    "ResourceLeaseNotFound",
    "ResourceLeaseOwnershipError",
    "ResourceLeaseStore",
    "ResourceLeaseStoreUnavailable",
    "ResourceOwner",
    "ResourceProvider",
    "ResourceRequest",
    "ResourceRequirement",
    "ResourceWaitTimeout",
    "cuda_environment_for_lease",
    "physical_gpu_index",
]
